/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author wperezp
 */
public class InfoPanel extends javax.swing.JPanel {
    
    BufferedImage frame;
    InfoPanelData data;

    /**
     * Creates new form InfoPanel
     * @param d
     */
    public InfoPanel(InfoPanelData d) {
        initComponents();
        data = d;
        frame = new BufferedImage(200, 420, BufferedImage.TYPE_INT_RGB);
        try {
            Image srcFrame = ImageIO.read(new File("./res/jungle_frame.jpg"));
            Image sclFrame = srcFrame.getScaledInstance(200, 420, Image.SCALE_SMOOTH);
            frame.getGraphics().drawImage(sclFrame, 0, 0, null);
        } catch (IOException ex) {
            Logger.getLogger(InfoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        //Graphics gFrame = frame.getGraphics();
        //gFrame.drawString("Cosillas", 30, 30);
        g.drawImage(frame, 0, 0, this);
        g.drawString(data.avatar.getNombre(), 50, 50);
        g.drawString("Vida: " + data.avatar.getVidaActual(), 50, 70);
        g.drawString("Arma: " + data.avatar.getArmaActual().getNombre(), 50, 90);
        g.drawString("Armadura: " + data.avatar.getArmaduraActual().getNombre(), 50, 110);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
