/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import Controlador.GestorInteraccion;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DAVID
 */
public class PeleaDialog extends javax.swing.JDialog {

    private Avatar avatar;
    private Enemigo enemigo;
    private GestorInteraccion gestor;
    private DefaultListModel armaSeleccionada;
    private Saco saco;
    
    /**
     * Creates new form PeleaDialog
     * @param a
     * @param e
     * @param gi
     * @param parent
     * @param modal
     */
    public PeleaDialog(Avatar a, Enemigo e, GestorInteraccion gi, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        avatar = a;
        enemigo = e;
        gestor = gi;
        LoadDialogItems();
    }
    
    private void LoadDialogItems() {
        this.AvatarName.setText(avatar.GetNombre());
        this.AvatarVidaLbl.setText(String.format("%d", avatar.GetVidaActual()));
        this.AvatarAtaqueLbl.setText(String.format("%d", avatar.ArmaActual().GetMaxDamage()));
        this.AvatarDefensaLbl.setText(String.format("%d", avatar.ArmaduraActual().GetDefensa()));
        this.AvatarArmaLbl.setText(avatar.ArmaActual().Nombre());
        
        this.EnemigoName.setText(enemigo.GetNombre());
        this.EnemigoVidaLbl.setText(String.format("%d", enemigo.GetVidaActual()));
        this.EnemigoAtaqueLbl.setText(String.format("%d", enemigo.GetAtaque()));
        this.EnemigoDefensaLbl.setText(String.format("%d", enemigo.GetDefensa()));
        
        saco = avatar.Saco();
        int sacoSize = saco.Size();
        if (sacoSize > 0){            
            DefaultListModel dlm = new DefaultListModel();
            Artefacto art;
            for (int i = 0; i < sacoSize; i++) {
                art = saco.Get(i);       
                
                if (art instanceof Arma)
                    dlm.addElement(String.format("%d) Arma: ",i+1) + art.Nombre());     
                else if (art instanceof Armadura)
                    dlm.addElement(String.format("%d) Armadura: ",i+1) + art.Nombre());
            }
            listSaco.setModel(dlm);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        AvatarName = new javax.swing.JLabel();
        AtacarBtn = new javax.swing.JButton();
        HuirBtn = new javax.swing.JButton();
        UsarBtn = new javax.swing.JButton();
        EnemigoName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AvatarVidaLbl = new javax.swing.JLabel();
        AvatarAtaqueLbl = new javax.swing.JLabel();
        AvatarDefensaLbl = new javax.swing.JLabel();
        EnemigoVidaLbl = new javax.swing.JLabel();
        EnemigoAtaqueLbl = new javax.swing.JLabel();
        EnemigoDefensaLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSaco = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        labelArma = new javax.swing.JLabel();
        AvatarArmaLbl = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AvatarName.setText("jLabel1");

        AtacarBtn.setText("Atacar");
        AtacarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtacarBtnActionPerformed(evt);
            }
        });

        HuirBtn.setText("Huir");
        HuirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuirBtnActionPerformed(evt);
            }
        });

        UsarBtn.setText("Usar");
        UsarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsarBtnActionPerformed(evt);
            }
        });

        EnemigoName.setText("jLabel2");

        jLabel3.setText("Vida");

        jLabel4.setText("Ataque");

        jLabel5.setText("Defensa");

        jLabel6.setText("Vida");

        jLabel7.setText("Ataque");

        jLabel8.setText("Defensa");

        AvatarVidaLbl.setText("jLabel1");

        AvatarAtaqueLbl.setText("jLabel2");

        AvatarDefensaLbl.setText("jLabel9");

        EnemigoVidaLbl.setText("jLabel1");

        EnemigoAtaqueLbl.setText("jLabel2");

        EnemigoDefensaLbl.setText("jLabel9");

        jScrollPane1.setViewportView(listSaco);

        jLabel1.setText("Cosillas:");

        labelArma.setText("Arma");

        AvatarArmaLbl.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AvatarName)
                        .addGap(149, 149, 149)
                        .addComponent(EnemigoName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AtacarBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(labelArma))
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AvatarArmaLbl)
                                        .addComponent(AvatarAtaqueLbl)
                                        .addComponent(AvatarDefensaLbl)
                                        .addComponent(AvatarVidaLbl)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EnemigoVidaLbl)
                                    .addComponent(EnemigoAtaqueLbl)
                                    .addComponent(EnemigoDefensaLbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(HuirBtn)
                                .addGap(33, 33, 33)
                                .addComponent(UsarBtn)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvatarName)
                    .addComponent(EnemigoName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(AvatarVidaLbl)
                    .addComponent(EnemigoVidaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(AvatarAtaqueLbl)
                    .addComponent(EnemigoAtaqueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(AvatarDefensaLbl)
                    .addComponent(EnemigoDefensaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArma)
                    .addComponent(AvatarArmaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HuirBtn)
                    .addComponent(UsarBtn)
                    .addComponent(AtacarBtn))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtacarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtacarBtnActionPerformed
        gestor.interactuarEnemigo(avatar, enemigo);
        if (enemigo.GetVidaActual() <= 0) dispose();
    }//GEN-LAST:event_AtacarBtnActionPerformed

    private void HuirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuirBtnActionPerformed
        dispose();
    }//GEN-LAST:event_HuirBtnActionPerformed

    private void UsarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsarBtnActionPerformed
        //armaSeleccionada.addElement(listSaco.getSelectedValue());
        String selectedItem = listSaco.getSelectedValue();
        String[] sel = selectedItem.split(": ");
        
        Artefacto art = saco.Get(sel[1]);                 
        
        if (art instanceof Arma){
            Arma arma = (Arma)art;
            avatar.SetArmaActual(arma);
            JOptionPane.showMessageDialog(this, arma.Nombre(), "Arma seleccionada:", JOptionPane.INFORMATION_MESSAGE);
        }                         
        this.AvatarArmaLbl.setText(avatar.ArmaActual().Nombre());
        //cargarMeme();
    }//GEN-LAST:event_UsarBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtacarBtn;
    private javax.swing.JLabel AvatarArmaLbl;
    private javax.swing.JLabel AvatarAtaqueLbl;
    private javax.swing.JLabel AvatarDefensaLbl;
    private javax.swing.JLabel AvatarName;
    private javax.swing.JLabel AvatarVidaLbl;
    private javax.swing.JLabel EnemigoAtaqueLbl;
    private javax.swing.JLabel EnemigoDefensaLbl;
    private javax.swing.JLabel EnemigoName;
    private javax.swing.JLabel EnemigoVidaLbl;
    private javax.swing.JButton HuirBtn;
    private javax.swing.JButton UsarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelArma;
    private javax.swing.JList<String> listSaco;
    // End of variables declaration//GEN-END:variables
}
