/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import Controlador.GestorInteraccion;

/**
 *
 * @author DAVID
 */
public class PeleaDialog extends javax.swing.JDialog {

    private Avatar avatar;
    private Enemigo enemigo;
    private GestorInteraccion gestor;
    
    /**
     * Creates new form PeleaDialog
     */
    public PeleaDialog(Avatar a, Enemigo e, GestorInteraccion gi, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        avatar = a;
        enemigo = e;
        gestor = gi;
        cargarMeme();
    }
    
    private void cargarMeme() {
        this.AvatarName.setText(avatar.getNombre());
        this.AvatarVidaLbl.setText(String.format("%d", avatar.getVidaActual()));
        this.AvatarAtaqueLbl.setText(String.format("%d", avatar.getArmaActual().getDano_max()));
        this.AvatarDefensaLbl.setText(String.format("%d", avatar.getArmaduraActual().getDefensa()));
        
        this.EnemigoName.setText(enemigo.getNombre());
        this.EnemigoVidaLbl.setText(String.format("%d", enemigo.getVidaActual()));
        this.EnemigoAtaqueLbl.setText(String.format("%d", enemigo.getAtaque()));
        this.EnemigoDefensaLbl.setText(String.format("%d", enemigo.getDefensa()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AvatarName = new javax.swing.JLabel();
        AtacarBtn = new javax.swing.JButton();
        HuirBtn = new javax.swing.JButton();
        UsarBtn = new javax.swing.JButton();
        EnemigoName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AvatarVidaLbl = new javax.swing.JLabel();
        AvatarAtaqueLbl = new javax.swing.JLabel();
        AvatarDefensaLbl = new javax.swing.JLabel();
        EnemigoVidaLbl = new javax.swing.JLabel();
        EnemigoAtaqueLbl = new javax.swing.JLabel();
        EnemigoDefensaLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AvatarName.setText("jLabel1");

        AtacarBtn.setText("Atacar");
        AtacarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtacarBtnActionPerformed(evt);
            }
        });

        HuirBtn.setText("Huir");
        HuirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuirBtnActionPerformed(evt);
            }
        });

        UsarBtn.setText("Usar");
        UsarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsarBtnActionPerformed(evt);
            }
        });

        EnemigoName.setText("jLabel2");

        jLabel3.setText("Vida");

        jLabel4.setText("Ataque");

        jLabel5.setText("Defensa");

        jLabel6.setText("Vida");

        jLabel7.setText("Ataque");

        jLabel8.setText("Defensa");

        AvatarVidaLbl.setText("jLabel1");

        AvatarAtaqueLbl.setText("jLabel2");

        AvatarDefensaLbl.setText("jLabel9");

        EnemigoVidaLbl.setText("jLabel1");

        EnemigoAtaqueLbl.setText("jLabel2");

        EnemigoDefensaLbl.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AvatarName)
                                .addGap(149, 149, 149)
                                .addComponent(EnemigoName))
                            .addComponent(HuirBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(UsarBtn)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AtacarBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AvatarAtaqueLbl)
                                    .addComponent(AvatarDefensaLbl)
                                    .addComponent(AvatarVidaLbl))))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnemigoVidaLbl)
                            .addComponent(EnemigoAtaqueLbl)
                            .addComponent(EnemigoDefensaLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvatarName)
                    .addComponent(EnemigoName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(AvatarVidaLbl)
                    .addComponent(EnemigoVidaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(AvatarAtaqueLbl)
                    .addComponent(EnemigoAtaqueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(AvatarDefensaLbl)
                    .addComponent(EnemigoDefensaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtacarBtn)
                    .addComponent(HuirBtn)
                    .addComponent(UsarBtn))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtacarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtacarBtnActionPerformed
        gestor.interactuarEnemigo(avatar, enemigo);
        if (enemigo.getVidaActual() <= 0) dispose();
    }//GEN-LAST:event_AtacarBtnActionPerformed

    private void HuirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuirBtnActionPerformed
        dispose();
    }//GEN-LAST:event_HuirBtnActionPerformed

    private void UsarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsarBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtacarBtn;
    private javax.swing.JLabel AvatarAtaqueLbl;
    private javax.swing.JLabel AvatarDefensaLbl;
    private javax.swing.JLabel AvatarName;
    private javax.swing.JLabel AvatarVidaLbl;
    private javax.swing.JLabel EnemigoAtaqueLbl;
    private javax.swing.JLabel EnemigoDefensaLbl;
    private javax.swing.JLabel EnemigoName;
    private javax.swing.JLabel EnemigoVidaLbl;
    private javax.swing.JButton HuirBtn;
    private javax.swing.JButton UsarBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
