//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQuipu.EQuipuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EQuipuService.IEQuipuService")]
    public interface IEQuipuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEQuipuService/ValidarUsuario", ReplyAction="http://tempuri.org/IEQuipuService/ValidarUsuarioResponse")]
        bool ValidarUsuario(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEQuipuService/ValidarUsuario", ReplyAction="http://tempuri.org/IEQuipuService/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usuario, string contraseña);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEQuipuServiceChannel : EQuipu.EQuipuService.IEQuipuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EQuipuServiceClient : System.ServiceModel.ClientBase<EQuipu.EQuipuService.IEQuipuService>, EQuipu.EQuipuService.IEQuipuService {
        
        public EQuipuServiceClient() {
        }
        
        public EQuipuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EQuipuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EQuipuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EQuipuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string usuario, string contraseña) {
            return base.Channel.ValidarUsuario(usuario, contraseña);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usuario, string contraseña) {
            return base.Channel.ValidarUsuarioAsync(usuario, contraseña);
        }
    }
}
